### ISSUE TITLE
circular icons

### ISSUE THREAD

**Issue by abhijeetbhagat** [bpierre/blo#4]
hey @bpierre instead of the default square shaped icons, i want to generate circular icons. i tried changing the path from square to a circle in `svg.ts` but the circle isnt getting rendered. any help would be appreciated.

**Comment by abhijeetbhagat** [comment]
never mind! i just found that i can set the `border-radius` css property on an `img` tag :)

**Comment by bpierre** [comment]
@abhijeetbhagat great :) btw is #3 still an issue?

**Comment by abhijeetbhagat** [comment]
@bpierre i did not get a chance to investigate it. as a workaround, being a naive react/js dev, i made your library part of our codebase. i'll show you soon how the icons look like :)

**Comment by bpierre** [comment]
I see, thanks for the update :)

**Comment by abhijeetbhagat** [comment]
@bpierre here's how the icons look like: https://holesky.chainlens.com/accounts

**Comment by bpierre** [comment]
@abhijeetbhagat Looking good! :tada:
